# Generated by Django 4.2.11 on 2024-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_group_deleted_at_group_restored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
