# Generated by Django 4.2.11 on 2024-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_added_by_user_group_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
